---
title: "R Code der Vorlesung BSc Statistik und Bioinformatik"
author: "Florian Hartig"
abstract: "Dieses Dokument fasst den in der Vorlesung live vorgeführten R Code zusammen. Wichtig: es handelt sich hier um eine Sammlung von Code, nicht um ein Lehrbuch. Insbesondere kann dieses Dokument die in der Vorlesung gegebene mündliche Erklärung der Motivation / Outputs nicht ersetzen. Bezüglich letztere verweise ich auf Ihre Mitschriften, die Vorlesungsunterlagen und das Skript."
format: 
  html:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r, echo=F}
set.seed(123)
```

# Woche 1 - Univariate deskriptive Statistik

## Einführung R

```{r}
2+2
sqrt(5)
barplot(c(1,2,3))

var1 = 5
var1 = c(1,2,3)
var2 = factor(c("rot", "gruen", "blau"))

mean(var1)
mean(var2)

dat = data.frame(var1 = var1, var2 = var2)
dat$var1
str(dat)

# das ist ein Kommentar
# Hilfe von Funktionen über ?name oder Maus auf Funktion und F1 drücken
```

## Zentraler Grenzwertsatz

```{r}
x = rlnorm(500)
hist(x, breaks = 50)

y = replicate(2000,mean(rlnorm(2000)))
hist(y, breaks = 50)
```

## Beispiel deskriptive Statistik mit realen Daten

Hier benutzen wir Daten der Passigierliste der Titanic. Die Daten sind im EcoData package enthalten. Um das EcoData package zu installieren, folgen Sie den Anweisungen [hier](https://theoreticalecology.github.io/AdvancedRegressionModels/1A-GettingStarted.html#libraries-that-you-will-need)

```{r}
library(EcoData)

str(titanic)

titanic$pclass = factor(titanic$pclass)
x = table(titanic$pclass)
x
barplot(x)
barplot(x, las = 2, horiz = T, col = c("darkred"))

x = table(titanic$sex)
x
barplot(x)

hist(titanic$age)
hist(titanic$age[titanic$pclass == 3])

mean(titanic$age, na.rm = T)
median(titanic$age, na.rm = T)
var(titanic$age, na.rm = T)
sd(titanic$age, na.rm = T)

quantile(titanic$age, na.rm = T)
boxplot(titanic$age)

# um moments zu installieren tippen Sie install.packages("moments")
library(moments)
skewness(titanic$age, na.rm = T)

```

# Woche 2

# Woche 3

# Woche 4

# Woche 5

# Woche 6

# Woche 7
